dependencies:
- name: zookeeper
  version: 7.0.6
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 10.5.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
